#!/usr/bin/env node

try {
  var reporter = require('nodeunit').reporters.default;
  var gossiper = require('gossiper');
}
catch(e) {
  console.log(e.message);
  console.log("");
  console.log("Cannot find required modules.");
  console.log("You can intall modules for this project by doing:");
  console.log("");
  console.log("    npm install");
  console.log("");
  process.exit();
}

process.chdir(__dirname);
reporter.run(['test', 'test/lib']);
