#!/usr/bin/env node

require.paths.push(__dirname);
require.paths.push(__dirname + "/lib");                                         

try {
  var reporter = require('nodeunit').reporters.default;
}
catch(e) {
  console.log(e.message);
  console.log("");
  console.log("Cannot find nodeunit module.");
  console.log("You can download submodules for this project by doing:");
  console.log("");
  console.log("    git submodule init");
  console.log("    git submodule update");
  console.log("");
  process.exit();
}

process.chdir(__dirname);
reporter.run(['test', 'test/lib']);
